### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by jaylac2000** [AJMyers1991/qb-firegear#1]
this will only work for male clothes

needs working out to detect gender and clothes as eup is different numbers for everything for both genders

**Comment by AJMyers1991** [comment]
I am currently working on a different way to get genders.  I'm almost done
so expect an update soon!

Thanks!
     Alexander Myers
     903-445-1827

**Comment by AJMyers1991** [comment]
Fixed!

**Comment by jaylac2000** [comment]
Sweet!! Thanks
